import { MessageCircle, Sparkles } from 'lucide-react'
import type { View } from './types'
import type { Challenge, TestCaseResult } from './api'
import { CodeEditor } from './CodeEditor'

type Props = { view: View; challenge: Challenge; code: string; setCode: (value: string) => void; run: () => void; running: boolean; stdout: string; stderr: string; result: string; caseResults: TestCaseResult[] }
export function PracticePanel({ view, challenge, code, setCode, run, running, stdout, stderr, result, caseResults }: Props) {
  const title = view === 'practice' ? 'Práctica guiada' : view === 'review' ? 'Code review' : 'Entrevista técnica'
  return <div className="space-y-7"><div><div className="eyebrow text-mint">{view === 'practice' ? 'MODO ENTRENAMIENTO' : view === 'review' ? 'MODO REVISIÓN' : 'MODO ENTREVISTA'}</div><h1 className="page-title">{title}</h1><p className="mt-3 text-slate-400">Ejecuta tu solución contra los casos de prueba guardados para este reto.</p></div><div className="grid gap-6 xl:grid-cols-[0.85fr_1.15fr]"><section className="panel"><div className="flex items-center justify-between"><span className="status-pill active">RETO ACTIVO</span><span className="text-xs text-slate-500">{challenge.difficulty} · {challenge.language}</span></div><h2 className="mt-6 font-display text-2xl font-semibold">{challenge.title}</h2><p className="mt-4 leading-7 text-slate-300">{challenge.prompt}</p><div className="mt-8 border-l-2 border-mint pl-4 text-sm leading-6 text-slate-400"><MessageCircle size={16} className="mb-2 text-mint" />Piensa en entradas vacías, valores límite y el contrato de salida.</div><div className="mt-8 rounded-xl border border-line bg-[#0a141c] p-4"><div className="flex items-center gap-2 text-xs text-slate-400"><Sparkles size={14} className="text-amber" /> Casos persistidos</div><p className="mt-3 text-sm leading-6 text-slate-300">{challenge.test_cases?.length ?? 0} casos se evaluarán en el servidor.</p></div>{caseResults.length > 0 && <div className="mt-8 space-y-3"><div className="eyebrow text-aqua">RESULTADOS POR CASO</div>{caseResults.map((item, index) => <div key={`${index}-${String(item.input)}`} className="rounded-xl border border-line bg-[#0a141c] p-3 text-sm"><div className="flex items-center gap-2"><span className={item.passed ? 'text-mint' : 'text-coral'}>{item.passed ? '✓' : '✕'}</span><span className={item.passed ? 'text-mint' : 'text-coral'}>Caso {index + 1}</span></div>{!item.passed && <div className="mt-2 space-y-1 text-xs text-slate-400"><div>Entrada: <span className="font-mono text-slate-300">{JSON.stringify(item.input)}</span></div><div>Esperado: <span className="font-mono text-slate-300">{JSON.stringify(item.expected)}</span></div><div>Obtenido: <span className="font-mono text-coral">{JSON.stringify(item.actual)}</span></div></div>}</div>)}</div>}</section><section><CodeEditor code={code} language={challenge.language} onChange={setCode} onRun={run} running={running} stdout={stdout || result} stderr={stderr} /></section></div></div>
}
